// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.12.4
// source: some_type.proto

package testdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SomeData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	I             int32                  `protobuf:"varint,2,opt,name=i,proto3" json:"i,omitempty"`
	L             []string               `protobuf:"bytes,3,rep,name=l,proto3" json:"l,omitempty"`
	Recursive     *SomeData              `protobuf:"bytes,4,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SomeData) Reset() {
	*x = SomeData{}
	mi := &file_some_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SomeData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SomeData) ProtoMessage() {}

func (x *SomeData) ProtoReflect() protoreflect.Message {
	mi := &file_some_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SomeData.ProtoReflect.Descriptor instead.
func (*SomeData) Descriptor() ([]byte, []int) {
	return file_some_type_proto_rawDescGZIP(), []int{0}
}

func (x *SomeData) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *SomeData) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *SomeData) GetL() []string {
	if x != nil {
		return x.L
	}
	return nil
}

func (x *SomeData) GetRecursive() *SomeData {
	if x != nil {
		return x.Recursive
	}
	return nil
}

var File_some_type_proto protoreflect.FileDescriptor

var file_some_type_proto_rawDesc = string([]byte{
	0x0a, 0x0f, 0x73, 0x6f, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a, 0x08, 0x53,
	0x6f, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x01, 0x69, 0x12, 0x0c, 0x0a, 0x01, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x01,
	0x6c, 0x12, 0x30, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73, 0x69, 0x76, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2e,
	0x53, 0x6f, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x72, 0x65, 0x63, 0x75, 0x72, 0x73,
	0x69, 0x76, 0x65, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6a, 0x66, 0x6d, 0x61, 0x74, 0x74, 0x2f, 0x67, 0x6f, 0x74, 0x65, 0x73, 0x74, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_some_type_proto_rawDescOnce sync.Once
	file_some_type_proto_rawDescData []byte
)

func file_some_type_proto_rawDescGZIP() []byte {
	file_some_type_proto_rawDescOnce.Do(func() {
		file_some_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_some_type_proto_rawDesc), len(file_some_type_proto_rawDesc)))
	})
	return file_some_type_proto_rawDescData
}

var file_some_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_some_type_proto_goTypes = []any{
	(*SomeData)(nil), // 0: testdata.SomeData
}
var file_some_type_proto_depIdxs = []int32{
	0, // 0: testdata.SomeData.recursive:type_name -> testdata.SomeData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_some_type_proto_init() }
func file_some_type_proto_init() {
	if File_some_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_some_type_proto_rawDesc), len(file_some_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_some_type_proto_goTypes,
		DependencyIndexes: file_some_type_proto_depIdxs,
		MessageInfos:      file_some_type_proto_msgTypes,
	}.Build()
	File_some_type_proto = out.File
	file_some_type_proto_goTypes = nil
	file_some_type_proto_depIdxs = nil
}
